---
- name: Common setup for all Pi nodes
  hosts: all
  become: true
  roles:
    - common

- name: Setup lead node
  hosts: lead
  become: true
  roles:
    - lead

- name: Setup worker nodes
  hosts: workers
  become: true
  roles:
    - worker
